export const settingsInputsData = [
  {
    type: 'email',
    placeholder: 'Введите логин или email',
    className: 'input',
    name: 'email',
    required: 'required',
    value: 'test@yandex.ru',
  },
  {
    type: 'text',
    placeholder: 'Имя',
    className: 'input',
    name: 'first_name',
    required: 'required',
    value: 'Test',
  },
  {
    type: 'text',
    placeholder: 'Фамилия',
    className: 'input',
    name: 'second_name',
    required: 'required',
    value: 'Testovich',
  },
  {
    type: 'text',
    placeholder: 'Login',
    className: 'input',
    name: 'login',
    required: 'required',
    value: 'Test',
  },
  {
    type: 'tel',
    placeholder: 'Tелефон',
    className: 'input',
    name: 'phone',
    required: 'required',
    value: '+79995558832',
  },
  {
    type: 'text',
    placeholder: 'Имя в чате',
    className: 'input',
    name: 'display_name',
    required: 'required',
    value: 'TestRock',
  },
  {
    type: 'password',
    placeholder: 'Пароль',
    className: 'input',
    name: 'oldPassword',
    required: 'required',
    value: '5591hgj788',
  },
  {
    type: 'password',
    placeholder: 'Новый пароль',
    className: 'input',
    name: 'newPassword',
    value: '',
  },
];
