export const registrationInputsData = [
  {
    type: 'email',
    placeholder: 'Введите логин или email',
    className: 'input',
    name: 'email',
    required: 'required',
    value: '',
  },
  {
    type: 'text',
    placeholder: 'Имя',
    className: 'input',
    name: 'first_name',
    required: 'required',
    value: '',
  },
  {
    type: 'text',
    placeholder: 'Фамилия',
    className: 'input',
    name: 'second_name',
    required: 'required',
    value: '',
  },
  {
    type: 'text',
    placeholder: 'Login',
    className: 'input',
    name: 'login',
    required: 'required',
    value: '',
  },
  {
    type: 'tel',
    placeholder: 'Телефон',
    className: 'input',
    name: 'phone',
    required: 'required',
    value: '',
  },
  {
    type: 'password',
    placeholder: 'Пароль',
    className: 'input',
    name: 'password',
    required: 'required',
    value: '',
  },
];
